export const TODAY_MIDNIGHT = new Date()
TODAY_MIDNIGHT.setHours(0, 0, 0, 0)

export const AI_GENERATED_TODO_TITLES = [
  'Fix mobile nav toggle not closing on click',
  'Fix issue where mobile nav overlaps content when keyboard is open on small Android devices',
  'Refactor login component to use hooks',
  'Refactor authentication flow to include token refresh and handle backend timeout scenarios',
  'Add hover styles to primary buttons',
  'Add animated loading spinner with accessibility support for dashboard data-fetching sections',
  'Align text in footer links',
  'Update footer layout to include terms, privacy policy, and contact support information',
  'Remove unused images from assets',
  'Audit and clean up unused utility classes from Tailwind CSS and global stylesheet files',
  'Update favicon with new branding',
  'Optimize hero image with WebP fallback and preload for improved first contentful paint',
  'Fix modal scroll lock issue',
  'Fix z-index conflict in modals causing overlay issues with headers and tooltips',
  'Center-align login form content',
  'Improve form accessibility by adding proper ARIA labels and keyboard tab support',
  'Enable focus ring on buttons',
  'Ensure all interactive components have visible focus styles and consistent tab ordering',
  'Shorten mobile menu transition time',
  'Fix layout breaking issues in Firefox due to unsupported flex shorthand values',
  'Add link to FAQ in footer',
  'Create responsive FAQ accordion with accessible expand/collapse interactions',
  'Clean up console warnings',
  'Replace deprecated lifecycle methods in all React components with functional equivalents',
  'Increase padding in table rows',
  'Ensure all data table rows have consistent vertical spacing on desktop and mobile views',
  'Remove inline styles in header',
  'Move all inline styles to utility classes or component-scoped styles for maintainability',
  'Fix nav item active highlight',
  'Highlight active nav item based on current route and ensure visual indication is clear',
  'Add alt text to logos',
  'Add descriptive alt text to all logos and decorative icons for improved accessibility',
  'Fix dropdown closing bug',
  'Ensure dropdown menus close on outside click and escape key with proper ARIA roles',
  'Use consistent box shadows',
  'Standardize button and card shadow styles across app for visual consistency',
  'Fix misaligned icons',
  'Adjust spacing on icon and text buttons to ensure alignment across all screen sizes',
  'Fix broken link in footer',
  'Update footer links to use dynamic routing and validate all external URLs for correctness',
  'Center loading spinner',
  'Create animated spinner with motion preferences respected and smooth fade transitions',
  'Add aria-labels to icons',
  'Ensure all non-text icons used in buttons or links have appropriate ARIA labels for screen readers',
  'Fix spacing under section headers',
  'Use utility classes to maintain consistent spacing above and below all section headers',
  'Disable button on submit',
  'Prevent duplicate form submissions by disabling submit button and showing loading feedback',
  'Fix typo in confirmation text',
  'Update confirmation dialogs to use consistent messaging and correct grammar/punctuation',
  'Reorder settings tabs',
  'Reorganize settings tab layout to match new product requirements and prioritize visibility',
  'Update site title tag',
  'Update page <title> dynamically per route for better SEO and page context awareness',
  'Fix search bar overflow issue',
  'Debounce input in global search bar to limit requests and prevent overflow on mobile',
  'Add back-to-top button',
  'Implement floating back-to-top button with smooth scroll and fade-in on long scroll pages',
  'Fix checkbox label alignment',
  'Ensure checkbox labels align properly across different devices and font sizes',
  'Optimize images in blog posts',
  'Run all blog post images through image compression and serve optimized formats (e.g., WebP)',
  'Standardize font weights',
  'Ensure font weights for headings and body text follow consistent typography scale',
  'Fix login redirect bug',
  'Fix bug where users are redirected incorrectly after login when navigating from nested routes',
  'Limit input to 100 chars',
  'Add character limit and real-time counter to input fields with clear validation feedback',
  'Make logo link to home',
  'Ensure clicking logo always routes to homepage and uses accessible navigation',
  'Add copy button to code blocks',
  'Implement copy-to-clipboard button for all code snippets with visual feedback on click',
  'Fix dropdown icon rotation',
  'Rotate dropdown chevron smoothly with transition and ensure state reflects open/closed state',
  'Update site meta description',
  'Write clear meta descriptions for each page to improve SEO and search engine previews',
  'Fix dark mode toggle flash',
  'Prevent flash of unstyled content when switching themes by preloading dark mode classes',
  'Fix profile avatar update bug',
  'Ensure updated avatars reflect immediately after upload and cache is cleared appropriately',
  'Add support contact form',
  'Create dynamic contact form with input validation, error handling, and success state feedback',
  'Fix tooltip clipping on scroll',
  'Position tooltips dynamically to prevent overflow and ensure visibility near viewport edges',
  'Add favicon to all pages',
  'Ensure favicon loads correctly across all routes and browsers using appropriate link tags',
  'Fix input border color',
  'Standardize input borders for light and dark themes using token-based color variables',
  'Adjust modal animation speed',
  'Speed up modal transition animations for snappier UX without breaking accessibility',
  'Fix alert component margin',
  'Ensure alert components have consistent top/bottom spacing and responsive layout handling',
  'Remove debug console logs',
  'Remove all console logs and debug statements before production deployment',
  'Fix toast positioning',
  'Align toast notifications correctly for mobile and desktop viewports with consistent stacking',
  'Fix text overflow in buttons',
  'Ensure button labels truncate with ellipsis and stay aligned in tight layouts',
  'Fix broken image paths',
  'Gracefully handle broken or missing images with fallback source and lazy loading',
  'Remove unused CSS rules',
  'Audit compiled stylesheets for unused selectors and clean up to reduce CSS bundle size',
  'Fix padding in tag chips',
  'Ensure consistent padding in tag components for better alignment with text content',
  'Add keyboard nav to carousel',
  'Implement keyboard arrow and focus support for carousel elements with accessible labels',
  'Add hover state to tabs',
  'Create distinct hover state for tabs to improve discoverability and match design system',
  'Fix sticky header bug',
  'Resolve bug where sticky header overlaps modals or pushes content incorrectly on scroll',
  'Add support for SVG uploads',
  'Extend file uploader to accept SVG with validation and sanitize before rendering inline',
  'Fix user card layout issue',
  'Ensure profile cards stack and align properly in grid and list layouts on all breakpoints',
  'Remove deprecated imports',
  'Audit and remove unused or deprecated imports across all components and utilities',
  'Fix dropdown alignment',
  'Align dropdown menus to toggle buttons with smart positioning to avoid clipping',
  'Fix broken breadcrumb nav',
  'Ensure breadcrumb navigation dynamically reflects nested page routes and URL segments',
  'Improve error page copy',
  'Rewrite error messages on 404 and 500 pages to be more helpful, human, and brand-aligned',
  'Fix tab key skipping buttons',
  'Ensure tabbing order includes all interactive elements and respects logical page flow',
  'Fix vertical overflow on modal',
  'Enable vertical scroll for long modal content without breaking layout or hiding actions',
  'Fix inconsistent button height',
  'Ensure all button types use consistent padding and font size across design variants',
  'Fix wrong font in headings',
  'Apply correct font family and weight to heading tags for branding consistency',
]
